schema_version: 1

context:
  name: ldas-tools-ldasgen
  version: "2.7.8"
  ldas_tools_al_version: 2.10.0
  ldas_tools_cmake_version: 1.5.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://software.ligo.org/sources/source/${{ name }}-${{ version }}.tar.gz
  sha256: aece9fc8a9878853cf9615c67a8db31d6245605923ce26da8f1ac3a690f1625c

build:
  dynamic_linking:
    overdepending_behavior: error
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake >=3.12,<4.0.0a0
    - make
    - pkg-config
  host:
    - libboost-headers
    - ldas-tools-al >=${{ ldas_tools_al_version }}
    - ldas-tools-cmake >=${{ ldas_tools_cmake_version }}
  run_exports:
    - ${{ pin_subpackage("ldas-tools-ldasgen", upper_bound="x.x") }}

tests:
  - package_contents:
      lib:
        - ldasgen
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --print-errors --exact-version ${{ version }} ldastools-ldasgen

about:
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Filters library used by ldas-tools
  description: |
    This provides the runtime libraries for the filters library.


  homepage: https://wiki.ligo.org/Computing/LDASTools
  repository: https://git.ligo.org/ldastools/LDAS_Tools.git

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
